### ISSUE TITLE
Fix minor layout changes in core

### ISSUE THREAD

**Issue by phiw13** [jools-r/glz_custom_fields#1]
The plugin will need some minor change as Core has slightly modified the layout of the list panels. In short, the @.txp-control-panel@ needs to be wrapped inside an additional `div` with classes: `txp-layout-cell-row txp-list-head`

Tentative diff below

```
@@ -2247,11 +2247,12 @@
                 hed(gTxt('glz_cf_tab_name'), 1, array('class' => 'txp-heading')).
             tag_end('div').
             tag_start('div', array('class' => 'txp-layout-2col')).
                 href(gTxt('tab_preferences'), '?event=prefs#prefs_group_glz_custom_f', array('class' => 'glz-cf-setup-switch')).
             tag_end('div').
-            tag_start('div', array('class' => 'txp-layout-1col', 'id' => $event.'_container'));
+            tag_start('div', array('class' => 'txp-layout-1col', 'id' => $event.'_container')).
+            tag_start('div', array('class' => 'txp-layout-cell-row txp-list-head'));
 
     // 'Add new custom field' button
     $out[] =
         n.tag(
             href(
@@ -2267,10 +2268,12 @@
                 )
             ),
             'div',
             array('class' => 'txp-control-panel')
         );
+        
+      $out[] = n.tag_end('div');
```

**Comment by jools-r** [comment]
Thank you for your diff. On reflection I opted here to disable the list options as they are of limited use for so few columns and can interfere with the drag-sorting. They didn't originally appear, either, so must fire automatically now on tables with `.txp-list`. I've accommodated some of your earlier suggestions, though. See the forum thread.

**Comment by jools-r** [comment]
Now as link as you suggested. Incorporated and recompiled along with updated help infos.
