### ISSUE TITLE
incorrect URL in the textpack

### ISSUE THREAD

**Issue by phiw13** [jools-r/glz_custom_fields#2]
The various URL in the message pane about incorrect name / invalid characters for custom fields names point to incorrect part of the help file

Sample (line 14) [here](https://github.com/jools-r/glz_custom_fields/blob/dev/textpacks/en-gb.textpack#L14) and following

It should point to `#plugin_help_section_custom_field_name` instead of `#plugin_help_section_special_custom_fields`.

**Comment by jools-r** [comment]
Thanks for testing so diligently, Philippe! Modified, checked and incorporated.
