### ISSUE TITLE
Support for TXT 4.8.5 & PHP 8.00

### ISSUE THREAD

**Issue by cara-tm** [jools-r/glz_custom_fields#6]
Removing the `$contents` parameter into this function deletes all warning messages and makes the plugin capable for 4.8.5 & PHP 8.00:

    //-------------------------------------------------------------
    // Button gets more consistent styling across browsers rather than input type="submit"
    // included in this plugin until in makes it into TXP - if that ever happens...
    function glz_fButton($type, $name, $value, $class='', $id='', $title='', $onClick='', $disabled = false)
    {
	$o  = '<button type="'.$type.'" name="'.$name.'"';
	$o .= ' value="'.htmlspecialchars($value).'"';
	$o .= ($class)    ? ' class="'.$class.'"' : '';
	$o .= ($id)       ? ' id="'.$id.'"' : '';
	$o .= ($title)    ? ' title="'.$title.'"' : '';
	$o .= ($onClick)  ? ' onclick="'.$onClick.'"' : '';
	$o .= ($disabled) ? ' disabled="disabled"' : '';
	$o .= '>';
	$o .= 'Submit';
	$o .= '</button>';
	return $o;
    }

**Comment by jools-r** [comment]
Thanks Pat. In fact, if I'm not mistaken, the entire function can go as it is not used in v2 anymore.

The other resolution is to place `$value` before  `$content='Submit'` in the list of attributes.

**Comment by jools-r** [comment]
Should be resolved with 23e8413cb2ddc7bd66683ff70dc6498cebc87398.
